input {
  beats {
    port => 5044
  }
}

filter {
  if "audit" in [log][file][path] {
    mutate {
      add_field => { "log_type" => "auditd" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "YOUR_PASSWORD"
    ssl => true
    ssl_certificate_verification => false
    index => "logstash-audit-%{+YYYY.MM.dd}"
  }
}